# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    active: false

style:
  ReturnCount:
    active: false
  MagicNumber:
    active: false

complexity:
  LongMethod:
    active: false